import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "./lib/queryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nizom System",
  description: "Generated by Fani",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bgBody`}>
        <QueryClientProvider client={queryClient}>
          <main className="mx-auto max-w-6xl py-14 px-3">{children}</main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
